INSERT INTO PTS_ACCOUNT(ACCOUNT_ID, USER_ACCOUNT_ID, IBAN, BALANCE)
VALUES (NEXT VALUE FOR SEQ_ACCOUNT, 1, 'ES2931909776197462913841', 0.0);

INSERT INTO PTS_TRANSACTION(TRANSACTION_ID, CONCEPT, DATE, AMOUNT, ACCOUNT_ID, CURRENT_STATUS)
VALUES (NEXT VALUE FOR SEQ_TRANSACTION, 'TEST TRANSACTION', CURRENT_TIMESTAMP, 25.56, CURRENT VALUE FOR SEQ_ACCOUNT, 'CREATED');

INSERT INTO PTS_TRANSACTION_STATUS_DETAIL(TRANSACTION_STATUS_ID, TRANSACTION_ID, STATUS_UPDATE_DATE, STATUS)
VALUES (NEXT VALUE FOR SEQ_TRANSACTION_STATUS_DETAIL, CURRENT VALUE FOR SEQ_TRANSACTION, CURRENT_TIMESTAMP, 'CREATED');

